source: mimics/downloads/
target: mimics/jellyfin/
log level: info
developer mode: False
Media Meta:
  - 1080p
  - 1440p
  - 2160p
  - 4k
  - 720p
  - 576p
  - H264
  - H265
  - x265
  - x264
  - AV1
  - AVC
  - WEB-DL
  - Baha
  - FLAC
  - BDRip
  - HEVC
  - 10bit
  - 8bit
  - AAC
  - mp4
  - WebRip
  - GB
  - BD
  - 1920x1080 
  - x.264
  - opus
  - GB_CN
  - yuv420p
  - AC3
  - SRTx4
  - 2K
  - Ma10p
  - EAC3
  - DSNP
  - TEPES
  - DUBBED
  - NF
  - HDR
  - DDP5.1
  - JAPANESE
  - Smurf
  - BluRay
  - HQCAM
  - ESub
  - DTS-HD
  - Atmos.7.1
  - UHD
  - H.265
  - IMAX
  - MA.5.1
  - AMZN
  - Max
  - MA
  - TrueHD.7.1
  - HD
  - Atmos
  - Multi
  - DDPA.5.1
  - DV